version: '3'
services:
  app:
    #app_goの中にあるDockerfileの読み込み
    build: ./app_opencv
    container_name: "app_opencv"
    tty: true
    #ホストのディレクトリをコンテナにマウント
    volumes:
      - ./app_opencv/app:/home/$APP_NAME
